=== rogimn/webservices/dtd/cursos.dtd
<!ELEMENT cursos (curso+)>
<!ELEMENT curso (nome,semestres,coordenador)>
<!ATTLIST curso id CDATA #IMPLIED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT semestres (#PCDATA)>
<!ELEMENT coordenador (#PCDATA)>

=== rogimn/webservices/xml/cursos.xml
<?xml version="1.0"?>
<!DOCTYPE cursos SYSTEM "dtd/cursos.dtd">
<cursos>
  <curso id="11">
    <nome>12</nome>
    <semestres>2</semestres>
    <coordenador>Daniel Anderle</coordenador>
  </curso>
  <curso id="12">
    <nome>45</nome>
    <semestres>2</semestres>
    <coordenador>Daniel Anderle</coordenador>
  </curso>
  <curso id="13">
    <nome>asda</nome>
    <semestres>3</semestres>
    <coordenador>Daniel Varela</coordenador>
  </curso>
  <curso id="4">
    <nome>Bacharelado em Agronomia</nome>
    <semestres>8</semestres>
    <coordenador>Lidiane Visintin</coordenador>
  </curso>
  <curso id="2">
    <nome>Bacharelado em Sistemas de Informa&#xE7;&#xE3;o</nome>
    <semestres>8</semestres>
    <coordenador>Daniel Anderle</coordenador>
  </curso>
  <curso id="14">
    <nome>Curso do Rafael</nome>
    <semestres>5</semestres>
    <coordenador>Daniel Anderle</coordenador>
  </curso>
  <curso id="8">
    <nome>inserido</nome>
    <semestres>6</semestres>
    <coordenador>Rafael Speroni</coordenador>
  </curso>
  <curso id="9">
    <nome>inserido</nome>
    <semestres>6</semestres>
    <coordenador>Rafael Speroni</coordenador>
  </curso>
  <curso id="5">
    <nome>PROEJA</nome>
    <semestres>6</semestres>
    <coordenador>Rafael Speroni</coordenador>
  </curso>
  <curso id="15">
    <nome>sdfsdfdsfdsf</nome>
    <semestres>6</semestres>
    <coordenador>&#xC2;ngelo Frozza</coordenador>
  </curso>
  <curso id="3">
    <nome>T&#xE9;cnico em Inform&#xE1;tica Integrado</nome>
    <semestres>6</semestres>
    <coordenador>&#xC2;ngelo Frozza</coordenador>
  </curso>
  <curso id="1">
    <nome>Tecnologia em Sistemas para Internet - TSI</nome>
    <semestres>6</semestres>
    <coordenador>Rafael Speroni</coordenador>
  </curso>
  <curso id="10">
    <nome>teste</nome>
    <semestres>2</semestres>
    <coordenador>Rafael Speroni</coordenador>
  </curso>
  <curso id="7">
    <nome>teste2</nome>
    <semestres>4</semestres>
    <coordenador>Lidiane Visintin</coordenador>
  </curso>
</cursos>
