=== rogimn/webservices/dtd/disciplinas.dtd
<!ELEMENT disciplinas (disciplina+)>
<!ELEMENT disciplina (codigo,nome,carga,ementa,semestre,curso)>
<!ATTLIST disciplina id CDATA #IMPLIED>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT carga (#PCDATA)>
<!ELEMENT ementa (#PCDATA)>
<!ELEMENT semestre (#PCDATA)>
<!ELEMENT curso (#PCDATA)>

=== rogimn/webservices/xml/disciplinas.xml
<?xml version="1.0"?>
<!DOCTYPE disciplinas SYSTEM "dtd/disciplinas.dtd">
<disciplinas>
  <disciplina id="5">
    <codigo>STB0305</codigo>
    <nome>Algoritmos e T&#xE9;cnicas de Programa&#xE7;&#xE3;o</nome>
    <carga>90</carga>
    <ementa>Introdu&#xE7;&#xE3;o &#xE0; l&#xF3;gica de programa&#xE7;&#xE3;o. Conceitos b&#xE1;sicos sobre algoritmos. Algoritmos Estruturados: conceitos, estruturas de controle (seq&#xFC;&#xEA;ncia, sele&#xE7;&#xE3;o e repeti&#xE7;&#xE3;o)entrada e sa&#xED;da, atribui&#xE7;&#xE3;o; Operadores B&#xE1;sicos (Aritm&#xE9;ticos, Relacionais e L&#xF3;gicos); Resolu&#xE7;&#xE3;o de problemas usando algoritmos; Verifica&#xE7;&#xE3;o e corre&#xE7;&#xE3;o de algoritmos atrav&#xE9;s de testes de mesa; Implementa&#xE7;&#xF5;es de algoritmos em uma linguagem de programa&#xE7;&#xE3;o.Procedimentos e Fun&#xE7;&#xF5;es.</ementa>
    <semestre>1</semestre>
    <curso>Tecnologia em Sistemas para Internet - TSI</curso>
  </disciplina>
  <disciplina id="7">
    <codigo>STB0307</codigo>
    <nome>Banco de Dados I</nome>
    <carga>60</carga>
    <ementa>Conscientiza&#xE7;&#xE3;o do processo de leitura. Estrat&#xE9;gias de leitura. Gram&#xE1;tica aplicada da l&#xED;ngua inglesa. Reconhecimento de g&#xEA;neros textuais e aquisi&#xE7;&#xE3;o de vocabul&#xE1;rio. An&#xE1;lise textual de um g&#xEA;nero. Leitura intensiva de diversos g&#xEA;neros textuais da &#xE1;rea de Inform&#xE1;tica. Reda&#xE7;&#xE3;o acad&#xEA;mica.</ementa>
    <semestre>2</semestre>
    <curso>Tecnologia em Sistemas para Internet - TSI</curso>
  </disciplina>
  <disciplina id="11">
    <codigo>SIB0312</codigo>
    <nome>Desenvolvimento Web I</nome>
    <carga>60</carga>
    <ementa>Introdu&#xE7;&#xE3;o &#xE0; l&#xF3;gica de programa&#xE7;&#xE3;o. Conceitos b&#xE1;sicos sobre algoritmos. Algoritmos Estruturados: conceitos, estruturas de controle (seq&#xFC;&#xEA;ncia, sele&#xE7;&#xE3;o e repeti&#xE7;&#xE3;o)entrada e sa&#xED;da, atribui&#xE7;&#xE3;o; Operadores B&#xE1;sicos (Aritm&#xE9;ticos, Relacionais e L&#xF3;gicos); Resolu&#xE7;&#xE3;o de problemas usando algoritmos; Verifica&#xE7;&#xE3;o e corre&#xE7;&#xE3;o de algoritmos atrav&#xE9;s de testes de mesa; Implementa&#xE7;&#xF5;es de algoritmos em uma linguagem de programa&#xE7;&#xE3;o.Procedimentos e Fun&#xE7;&#xF5;es.</ementa>
    <semestre>5</semestre>
    <curso>Bacharelado em Sistemas de Informa&#xE7;&#xE3;o</curso>
  </disciplina>
  <disciplina id="12">
    <codigo>SIB0313</codigo>
    <nome>Desenvolvimento Web II</nome>
    <carga>60</carga>
    <ementa>Introdu&#xE7;&#xE3;o &#xE0; l&#xF3;gica de programa&#xE7;&#xE3;o. Conceitos b&#xE1;sicos sobre algoritmos. Algoritmos Estruturados: conceitos, estruturas de controle (seq&#xFC;&#xEA;ncia, sele&#xE7;&#xE3;o e repeti&#xE7;&#xE3;o)entrada e sa&#xED;da, atribui&#xE7;&#xE3;o; Operadores B&#xE1;sicos (Aritm&#xE9;ticos, Relacionais e L&#xF3;gicos); Resolu&#xE7;&#xE3;o de problemas usando algoritmos; Verifica&#xE7;&#xE3;o e corre&#xE7;&#xE3;o de algoritmos atrav&#xE9;s de testes de mesa; Implementa&#xE7;&#xF5;es de algoritmos em uma linguagem de programa&#xE7;&#xE3;o.Procedimentos e Fun&#xE7;&#xF5;es.</ementa>
    <semestre>6</semestre>
    <curso>Bacharelado em Sistemas de Informa&#xE7;&#xE3;o</curso>
  </disciplina>
  <disciplina id="9">
    <codigo>STB0309</codigo>
    <nome>Engenharia de Software I</nome>
    <carga>60</carga>
    <ementa>Infraestrutura do Ambiente Web; P&#xE1;ginas Est&#xE1;ticas e P&#xE1;ginas Din&#xE2;micas; Introdu&#xE7;&#xE3;o a Linguagem de Marca&#xE7;&#xE3;o HTML e suas evolu&#xE7;&#xF5;es; Folhas de Estilos (CSS); Introdu&#xE7;&#xE3;o a Programa&#xE7;&#xE3;o Client-Side (JavaScript); Princ&#xED;pios para Web Design Responsivo.</ementa>
    <semestre>2</semestre>
    <curso>Tecnologia em Sistemas para Internet - TSI</curso>
  </disciplina>
  <disciplina id="6">
    <codigo>STB0306</codigo>
    <nome>Estrutura de Dados</nome>
    <carga>60</carga>
    <ementa>Conjuntos Num&#xE9;ricos: Conjunto dos n&#xFA;meros Naturais; Conjunto dos n&#xFA;meros Inteiros; Conjunto dos n&#xFA;meros Racionais: Fra&#xE7;&#xF5;es e opera&#xE7;&#xF5;es com fra&#xE7;&#xF5;es.</ementa>
    <semestre>2</semestre>
    <curso>Tecnologia em Sistemas para Internet - TSI</curso>
  </disciplina>
  <disciplina id="2">
    <codigo>STB0302</codigo>
    <nome>Ingl&#xEA;s Instrumental</nome>
    <carga>60</carga>
    <ementa>Conscientiza&#xE7;&#xE3;o do processo de leitura. Estrat&#xE9;gias de leitura. Gram&#xE1;tica aplicada da l&#xED;ngua inglesa. Reconhecimento de g&#xEA;neros textuais e aquisi&#xE7;&#xE3;o de vocabul&#xE1;rio. An&#xE1;lise textual de um g&#xEA;nero. Leitura intensiva de diversos g&#xEA;neros textuais da &#xE1;rea de Inform&#xE1;tica. Reda&#xE7;&#xE3;o acad&#xEA;mica.</ementa>
    <semestre>1</semestre>
    <curso>Tecnologia em Sistemas para Internet - TSI</curso>
  </disciplina>
  <disciplina id="3">
    <codigo>STB0303</codigo>
    <nome>Introdu&#xE7;&#xE3;o &#xE0; Computa&#xE7;&#xE3;o</nome>
    <carga>30</carga>
    <ementa>Evolu&#xE7;&#xE3;o da computa&#xE7;&#xE3;o (tecnologias e usos). Modelos funcionais dos computadores. Sistemas de c&#xF3;digos e codecs. Sistemas operacionais. Linguagens de programa&#xE7;&#xE3;o. Sistemas de rede e Internet. Open Source/Free Software. O estado da arte. TI x Sustentabilidade.</ementa>
    <semestre>1</semestre>
    <curso>Tecnologia em Sistemas para Internet - TSI</curso>
  </disciplina>
  <disciplina id="4">
    <codigo>STB0304</codigo>
    <nome>Introdu&#xE7;&#xE3;o &#xE0; Programa&#xE7;&#xE3;o Web</nome>
    <carga>60</carga>
    <ementa>Infraestrutura do Ambiente Web; P&#xE1;ginas Est&#xE1;ticas e P&#xE1;ginas Din&#xE2;micas; Introdu&#xE7;&#xE3;o a Linguagem de Marca&#xE7;&#xE3;o HTML e suas evolu&#xE7;&#xF5;es; Folhas de Estilos (CSS); Introdu&#xE7;&#xE3;o a Programa&#xE7;&#xE3;o Client-Side (JavaScript); Princ&#xED;pios para Web Design Responsivo.</ementa>
    <semestre>1</semestre>
    <curso>Tecnologia em Sistemas para Internet - TSI</curso>
  </disciplina>
  <disciplina id="10">
    <codigo>STB0305</codigo>
    <nome>Programa&#xE7;&#xE3;o Web</nome>
    <carga>60</carga>
    <ementa>Introdu&#xE7;&#xE3;o &#xE0; l&#xF3;gica de programa&#xE7;&#xE3;o. Conceitos b&#xE1;sicos sobre algoritmos. Algoritmos Estruturados: conceitos, estruturas de controle (seq&#xFC;&#xEA;ncia, sele&#xE7;&#xE3;o e repeti&#xE7;&#xE3;o)entrada e sa&#xED;da, atribui&#xE7;&#xE3;o; Operadores B&#xE1;sicos (Aritm&#xE9;ticos, Relacionais e L&#xF3;gicos); Resolu&#xE7;&#xE3;o de problemas usando algoritmos; Verifica&#xE7;&#xE3;o e corre&#xE7;&#xE3;o de algoritmos atrav&#xE9;s de testes de mesa; Implementa&#xE7;&#xF5;es de algoritmos em uma linguagem de programa&#xE7;&#xE3;o.Procedimentos e Fun&#xE7;&#xF5;es.</ementa>
    <semestre>2</semestre>
    <curso>Tecnologia em Sistemas para Internet - TSI</curso>
  </disciplina>
  <disciplina id="8">
    <codigo>STB0308</codigo>
    <nome>Sistemas Operacionais</nome>
    <carga>60</carga>
    <ementa>Evolu&#xE7;&#xE3;o da computa&#xE7;&#xE3;o (tecnologias e usos). Modelos funcionais dos computadores. Sistemas de c&#xF3;digos e codecs. Sistemas operacionais. Linguagens de programa&#xE7;&#xE3;o. Sistemas de rede e Internet. Open Source/Free Software. O estado da arte. TI x Sustentabilidade.</ementa>
    <semestre>2</semestre>
    <curso>Tecnologia em Sistemas para Internet - TSI</curso>
  </disciplina>
</disciplinas>
