=== rogimn/webservices/dtd/professores.dtd
<!ELEMENT professores (professor+)>
<!ELEMENT professor (nome,email)>
<!ATTLIST professor id CDATA #IMPLIED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== rogimn/webservices/xml/professores.xml
<?xml version="1.0"?>
<!DOCTYPE professores SYSTEM "dtd/professores.dtd">
<professores>
  <professor id="1">
    <nome>Andr&#xE9; Moraes</nome>
    <email>a****s@ifc.edu.br</email>
  </professor>
  <professor id="2">
    <nome>&#xC2;ngelo Frozza</nome>
    <email>a****a@ifc.edu.br</email>
  </professor>
  <professor id="3">
    <nome>Daniel Anderle</nome>
    <email>d****e@ifc.edu.br</email>
  </professor>
  <professor id="4">
    <nome>Daniel Varela</nome>
    <email>d****a@ifc.edu.br</email>
  </professor>
  <professor id="7">
    <nome>Joao</nome>
    <email>joao@gmail.com</email>
  </professor>
  <professor id="6">
    <nome>Lidiane Visintin</nome>
    <email>l****n@ifc.edu.br</email>
  </professor>
  <professor id="5">
    <nome>Rafael Speroni</nome>
    <email>r****i@ifc.edu.br</email>
  </professor>
</professores>
